apiapp/urls.py
from django.urls import path
from .views import products_list, products_list_selected, cartitems, productdetail, getparameters
from paymentsystem.views import createorder
app_name = 'apiapp'

urlpatterns = [
    path('products-list', products_list, name='products-list'),
    path('products-list-selected', products_list_selected, name='products-list-selected'),
    path('cart/items', cartitems, name='cartitems'),
    path('cart/do-order', createorder, name='do-order'),
    path('product/<int:id>', productdetail, name='productdetail'),
    path('parameters', getparameters, name='getparameters'),#список значений параметра товара
]

baseapp/urls.py
from django.urls import path
from . import views
from .sitemap import ProductViewSitemap, CategoriesViewSitemap
from django.views.generic import RedirectView
from django.contrib.sitemaps.views import sitemap
app_name = 'baseapp'

sitemaps = {
    'dynamic': ProductViewSitemap,
    'category' :CategoriesViewSitemap,
}

favicon_view = RedirectView.as_view(url='/static/favicon.png', permanent=True)

urlpatterns = [
    path('robots.txt/', views.RobotsTxtView.as_view()),
    path('favicon.ico/', favicon_view),
    path('', views.index, name='home'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('category/<int:id>', views.categorylist, name='categorylist'),
    path('categoryselected', views.categoryselected, name='categoryselected'),
    path('add_request', views.add_request, name='add_request'),
    path('searchprod', views.searchprod, name='searchprod'),
    path('paymentsusses', views.paysus, name='paysus'),
    path('photoorder', views.photoorder, name='photoorder'),
    path('photoalbum', views.photoalbum, name='photoalbum'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
]

medals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baseapp.urls', namespace='baseapp')),
    path('cart/', include('ordersapp.urls', namespace='cart')),
    path('api/', include('apiapp.urls', namespace='apiapp')),
    path('payment/', include('paymentsystem.urls', namespace='payment')),
]

if settings.DEBUG:# не кешировать
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
from django.urls import path, include
from . import views
from baseapp.views import detail
app_name = 'ordersapp'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('detail', detail, name='detail'),
]

baseapp/models.py
from django.db import models
from PIL import Image
from medals.settings import STATIC_ROOT

# Create your models here.
INPUTKIND = [
    ('1', 'checkbox'),
    ('2', 'input'),
    ('3', 'select'),
    ]
# Модель категорий
class Categories(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Наименование вида товара')
    image = models.ImageField(blank=True, upload_to='categories/', verbose_name='Главное изображение вида товара')
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вид товара'
        verbose_name_plural = 'Виды товаров'
        ordering = ['title']

class Categorymedals(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Вид награды')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вид награды'
        verbose_name_plural = 'Виды наград'
        ordering = ['-id']

class Parameters(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Вид параметра')
    inputtype = models.CharField(blank=True, max_length=20, choices = INPUTKIND, verbose_name='Тип ввода')
    label = models.CharField(blank=False, max_length=180, verbose_name='Подпись')
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вид параметра'
        verbose_name_plural = 'Виды параметров'
        ordering = ['-id']

# Модель товаров
class Product(models.Model):
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name='Категория', related_name="category")
    medalcategory = models.ForeignKey(Categorymedals, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Вид награды', related_name="categorymedal")
    title = models.CharField(blank=False, max_length=180, verbose_name='Наименование товара')
    image = models.ImageField(blank=False, null=False, upload_to='products_imgs/', verbose_name='Главное изображение товара')
    price = models.IntegerField(blank=False, null=False, default=100, verbose_name='Цена')
    description = models.TextField(blank=True, null=True, verbose_name='Описание товара')
    parameters = models.ForeignKey(Parameters, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Параметр', related_name="parameter")

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return str(self.title)
    
    def save(self):
        super().save()
        img = Image.open(self.image.path)
        mask = Image.open(STATIC_ROOT + '/mask.png')
        mask_crop = mask.crop((0, 0, img.width, img.height))
        img.paste(mask_crop, (0, 0), mask_crop)
        img.save(self.image.path)

# Модель дополнительных изображений товаров
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='товар', related_name="imgs")
    image = models.ImageField(blank=True, upload_to='product_imgs/', verbose_name='Дополнительное изображение')
    
    class Meta:
        verbose_name = 'Дополнительное изображение'
        verbose_name_plural = 'Дополнительные изображения'

    def __str__(self):
        return str(self.image.url)
    
    def save(self):
        super().save()
        img = Image.open(self.image.path)
        mask = Image.open('mask.png')
        mask_crop = mask.crop((0, 0, img.width, img.height))
        img.paste(mask_crop, (0, 0), mask_crop)
        img.save(self.image.path)
    

class Callrequest(models.Model):
    number = models.CharField(blank=False, null=False, max_length=80, verbose_name='Номер телефона')
    dateandtame = models.DateTimeField(blank=False, null=False, auto_now_add=True, verbose_name='Дата и время')

    class Meta:
        verbose_name = 'Заказ обратного звонка'
        verbose_name_plural = 'Заказы обратного звонка'

    def __str__(self):
        return str(self.number)
    

    
class Bases(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Наименование основы(крепления)')
    image = models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение крепления')
    requireColor = models.BooleanField(default=False, verbose_name="Нужен ли выбор цвета")
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вид крепления'
        verbose_name_plural = 'Виды креплений'
        ordering = ['title']

class Examples(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Заголовок')
    about = models.TextField(blank=False, max_length=180, verbose_name='Описание')
    image = models.ImageField(blank=True, upload_to='examples/', verbose_name='Изображение')
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пример работы (слайдер)'
        verbose_name_plural = 'Примеры работ (слайдер)'
        ordering = ['title']

class ExampleImage(models.Model):
    image = models.ImageField(blank=True, upload_to='photogallery/', verbose_name='Фото фотогалереи')
    
    class Meta:
        verbose_name = 'Фото фотогалереи'
        verbose_name_plural = 'Фото фотогалереи'

    def __str__(self):
        return str(self.image.url)
    
    def save(self):
        super().save()
        img = Image.open(self.image.path)
        mask = Image.open(STATIC_ROOT + '/mask.png')
        mask_crop = mask.crop((0, 0, img.width, img.height))
        img.paste(mask_crop, (0, 0), mask_crop)
        img.save(self.image.path)

baseapp/views.py
from django.shortcuts import render, get_object_or_404
from datetime import datetime
from .models import Product, ProductImage, Categories, Categorymedals, Callrequest, Examples, ExampleImage
from paymentsystem.models import Orders
from django.db.models import Q
import urllib.request
import urllib.parse
from django.views.generic import TemplateView

# Create your views here.
def index(request):
    keywords = 'Орденские планки колодки крепления заказать купить Москва, купить Медали России, лазерная гравировка в Москве'
    description = 'Мы предлагаем широкий ассортимент орденских планок и колодок, услуги лазерной гравировки.'
    examples = Examples.objects.all()
    maintitle = 'Орденские планки и колодки лазерная гравировка'
    return render(request, 'baseapp/home.html', {
        'categories': categorytonav(),
        'keywords': keywords,
        'description': description,
        'examples': examples,
        'maintitle': maintitle,
    })

def detail(request, id):
    itemId = id
    product = get_object_or_404(Product, pk = itemId)
    imgs = product.imgs.all()
    broads = []
    print(product.category.id)
    broads.append(f'<li class="breadcrumb-item"><a href="../category/{ product.category.id }">{product.category}</a></li>')
    broads.append(f'<li class="breadcrumb-item active">{product.title}</li>')
    if product.category.id == 4:
        keywords = f'{product.title}, купить {product.title}, заказать планку {product.title} в Москве, купить планку {product.title}, {product.title} на офисную форму'
        description = f'В магазине планки.москва Вы можете заказать орденскую планку или колодку {product.title} на различных видах креплений и подложке'
    elif product.category.id == 5:
        keywords = f'купить {product.title}, заказать {product.title}, купить жетон с гравировкой номера в Москве, {product.title} гравировка'
        description = f'В магазине планки.москва Вы можете заказать {product.title} с гравировкой номера'
    elif product.category.id == 6:
        keywords = f'купить {product.title}, заказать {product.title}, купить нагрудный знак с гравировкой номера в Москве, {product.title} гравировка'
        description = f'В магазине планки.москва Вы можете заказать {product.title} с гравировкой номера'
    elif product.category.id == 7:
        keywords = f'купить сувенирный {product.title} в Москве, заказать {product.title} сувенирный, {product.title} в Москве'
        description = f'В магазине планки.москва Вы можете заказать {product.title} с гравировкой номера'
    elif product.category.id == 9:
        keywords = f'купить расходные материалы для изготовления орденских планок и колодок {product.title} в Москве'
        description = f'В магазине планки.москва Вы можете заказать или купить расходные материалы для изготовления орденских планок и колодок'
    else:
        keywords = f'{product.title}, купить {product.title}, заказать планку {product.title}, купить планку {product.title}, {product.title} на офисную форму'
        description = f'В магазине планки.москва Вы можете заказать орденскую планку или колодку {product.title} на различных видах креплений и подложке'
    return render(request, 'baseapp/detail.html', {
        'product': product,
        'categories': categorytonav(),
        'imgs': imgs,
        'broads': broads,
        'keywords': keywords,
        'description': description,
        })

def categorylist(request, id):
    categoryId = id
    category = get_object_or_404(Categories, pk = categoryId)
    broads = []
    broads.append(f'<li class="breadcrumb-item active">{category.title}</li>')
    medalstypes = Categorymedals.objects.all()
    keywords = f'{category.title}, заказать {category.title} в Москве'
    description = f'В магазине планки.москва Вы можете заказать {category.title}'
    return render(request, 'baseapp/catalog.html', {
        'categories': categorytonav(),
        'medalstypes': medalstypes,
        'category': category,
        'broads': broads,
        'keywords': keywords,
        'description': description,
        })

def categoryselected(request):
    if 'category' in request.GET:
        categoryId = request.GET['category']
    else:
        categoryId = '1'
    if 'itemtype' in request.GET:
        medaltypeId = request.GET['itemtype']
    else:
        medaltypeId = '1'
    medalstypes = Categorymedals.objects.all()
    category = get_object_or_404(Categories, pk = categoryId)
    keywords = f'{category.title}, заказать {category.title} в Москве'
    description = f'В магазине планки.москва Вы можете заказать {category.title}'
    broads = []
    broads.append(f'<li class="breadcrumb-item active">{category.title}</li>')
    return render(request, 'baseapp/catalog.html', {
        'categories': categorytonav(),
        'medalstypes': medalstypes,
        'medaltypeId': medaltypeId,
        'category': category,
        'keywords': keywords,
        'description': description,
        'broads': broads,
        })

def add_request(request):
    if request.method == 'GET':
        req = Callrequest()
        num = str(request.GET['phone_number'])
        req.number = num
        req.save()

        url = u'https://api.telegram.org/bot6359888423:AAGEfUcoYBAcutK4DzvSjkmlfxmPNh23qPQ/sendMessage'
        admins = ('628257666', '701668128',)
        trans_table = {ord(' ') : None, ord('-') : None, ord('(') : None, ord(')') : None}
        num = num.translate(trans_table)
        msgForTg = f'Заказан обратный звонок на номер {num}'
        for admin in admins:
            data = {'chat_id': admin, 'text': msgForTg, 'parse_mode': 'HTML'}
            url_values = urllib.parse.urlencode(data)
            full_url = url + '?' + url_values
            data = urllib.request.urlopen(full_url)
    return index(request)

def searchprod(request):
    search_query = request.GET.get('query')
    products = Product.objects.filter(Q(title__iregex=search_query))
    return render(request, 'baseapp/search.html', {
        'categories': categorytonav(),
        'products': products
        })

def photoorder(request):
    broads = []
    broads.append(f'<li class="breadcrumb-item active">Заказ по фото</li>')
    keywords = f'медаль заказать по фото, заказать изготовление планки'
    description = f'В магазине планки.москва Вы можете заказать орденскую планку по фото.'
    maintitle = 'Заказать орденскую планку по фото'
    return render(request, 'baseapp/photoorder.html', {
        'categories': categorytonav(),
        'broads': broads,
        'keywords': keywords,
        'description': description,
        'maintitle': maintitle,
        })

def photoalbum(request):
    photos = ExampleImage.objects.all()
    return render(request, 'baseapp/photoalbum.html', {
        'categories': categorytonav(),
        'photos': photos,
        })

def categorytonav():
    categories = Categories.objects.all()
    return categories

def paysus(request):
    order = get_object_or_404(Orders, pk = request.GET['order'])
    return render(request, 'baseapp/paysus.html', {
        'categories': categorytonav(),
        'order': order
        })

class RobotsTxtView(TemplateView):
    template_name = 'robots.txt'
    content_type = 'text/plain'

baseapp/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "layout/headers.html" %}
</head>
<body>
    {% csrf_token %}
    <div id="app" class="wrapper">
        <div class="content">
            {% include "layout/header.html" %}
            {% include "layout/navigation.html" %}
            {% include "layout/services.html" %}

            <section class="section works">
                <div class="container">
                    <h2 class="section-title">Примеры работ</h2>

                    <div id="carouselExampleControls" class="carousel slide works-slide" data-bs-ride="carousel">
                        <div class="carousel-inner">

                            {% for example in examples %}
                                {% if forloop.first %}                              
                                <div class="carousel-item active works-item">
                                    <img src="{{ example.image.url }}" class="d-block w-100 works-item-img" alt="{{ example.about }} заказать в Москве">
                                    <div class="works-item-content">
                                        <h3 class="works-item-title">{{ example.title }}</h3>
                                        <p class="works-item-text">{{ example.about }}</p>
                                        <a href="{% url 'baseapp:photoalbum' %}" class="works-item-link">Просмотр</a>
                                    </div>
                                </div>
                                {% else %}
                                <div class="carousel-item works-item">
                                    <img src="{{ example.image.url }}" class="d-block w-100 works-item-img" alt="{{ example.about }} заказать в Москве">
                                    <div class="works-item-content">
                                        <h3 class="works-item-title">{{ example.title }}</h3>
                                        <p class="works-item-text">{{ example.about }}</p>
                                        <a href="{% url 'baseapp:photoalbum' %}" class="works-item-link">Просмотр</a>
                                    </div>
                                </div>
                                {% endif %}
                            {% endfor %}

                        </div>
                        <button class="carousel-control-prev works-control works-control-prev" type="button"
                                data-bs-target="#carouselExampleControls"
                                data-bs-slide="prev">
                            <i class="fa-solid fa-chevron-left fa-2xl"></i>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next works-control works-control-next" type="button"
                                data-bs-target="#carouselExampleControls"
                                data-bs-slide="next">
                            <i class="fa-solid fa-chevron-right fa-2xl"></i>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </section>

            <section class="section contacts">
                <div class="container">
                    <div class="section-title contacts-title">Контакты</div>

                    <div class="row" style="gap: 20px 0">
                        <div class="col-12 col-md-6">
                            <div class="contacts-map">
                                <script type="application/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A4984cbb5adf3164b1f94359118c537e115b9e5380116b1f6b2dfd2960f6795cf&amp;width=600&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
                            </div>
                        </div>

                        <div class="col-12 col-md-6">
                            <div class="contacts-list">
                                <a class="contacts-list-item">
                                    <i class="fa-solid fa-location-dot fa-xl"></i>
                                    г. Москва, ул. 2 Фрунзенская д .10 к. 2
                                </a>

                                <a href="tel:8 (965)-296-09-09" class="contacts-list-item">
                                    <i class="fa-solid fa-phone fa-xl"></i>
                                    8 (993)-694-59-81
                                </a>

                                <a href="https://wa.me/79652960909" class="contacts-list-item">
                                    <i class="fa-brands fa-whatsapp fa-xl"></i>
                                    8-993-694-59-81
                                </a>

                                <a href="https://t.me/plankimoskva" target="_blank" class="contacts-list-item">
                                    <i class="fa-brands fa-telegram fa-xl"></i>
                                    8-993-694-59-81
                                </a>

                                <a href="mailto:planki.moskva@mail.ru" class="contacts-list-item">
                                    <i class="fa-solid fa-envelope fa-xl"></i>
                                    planki.moskva@mail.ru
                                </a>

                                <a class="contacts-list-item">
                                    <i class="fa-solid fa-clock fa-xl"></i>
                                    Время работы: Пн-Сб,  С 10:00 До 20:00
                                </a>

                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        {% include "layout/footer.html" %}
    </div>

<script type="application/javascript" defer src="{% static 'baseapp/js/bundle.js' %}"></script>
<script type="application/javascript" src="//code.jivo.ru/widget/vr84HCIabX" async></script>
</body>
</html>

baseapp/templates/layout/broat.html
    <!-- хлебюные крошки -->
    <div class="breadcrumb-wrapper">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="/">Главная</a></li>
                {% block broad %}
                    {% for broad in broads %}
                        {{ broad|safe }}
                    {% endfor %}
                {% endblock %}
            </ol>
        </div>
    </div>

baseapp/templates/layout/footer.html
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="footer-main">
                    <h1 class="footer-title"><a href="/">&copy; Планки.Москва</a></h1>
                </div>
            </div>

            <div class="col-12 col-md-4">
                <div class="footer-links">
                    {% include "layout/nav_categogies.html" %}
                    <a href="https://xn--80aqfclj.xn--80adxhks/garantii/" class="nav-link">Гарантии</a>
                </div>
            </div>

            <div class="col-12 col-md-4">
                <div class="footer-actions">
                    <a href="#" class="footer-up">
                        <i class="fa-solid fa-chevron-up"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>

</footer>

baseapp/templates/layout/header.html
{% load static %}
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
    m[i].l=1*new Date();
    for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
    k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
 
    ym(94248570, "init", {
         clickmap:true,
         trackLinks:true,
         accurateTrackBounce:true,
         webvisor:true
    });
 </script>
 <noscript><div><img src="https://mc.yandex.ru/watch/94248570" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
 <!-- /Yandex.Metrika counter -->
 
<header class="header">
    <div class="container">
        <div class="row header-inner">
            <div class="col-12 col-md-3">
                <a href="/" class="header-logo">
                    <img src="{% static 'baseapp/images/logo.jpg' %}" alt="">
                </a>
            </div>

            <div class="col-12 col-sm-12 col-md-5">
                <div class="header-callback">
                    <div class="header-callback-phone">
                        <a href="tel:+79652960909"><i class="fa-solid fa-phone"></i>8 (965) 296-09-09</a>
                    </div>
                    <div class="header-callback-link" data-bs-toggle="modal" data-bs-target="#callbackModal">
                        Заказать обратный звонок
                    </div>
                </div>
            </div>

            <div class="col-md-4 d-none d-md-block">
                <div class="site-search" data-method="GET" data-url="search">
                    <!-- API -->
                    <form action="{% url 'baseapp:searchprod' %}" method="get">
                        <input class="site-search-input header-search" name="query" type="text" value="" placeholder="Поиск по сайту"/>
                        <a class="site-search-btn">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- модалка формы обратной связи -->
    <div class="modal fade" id="callbackModal" tabindex="-1" aria-labelledby="callbackModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="callbackModalLabel">Заказать обратный звонок</h5>
                    <button type="button" class="btn-outline" data-bs-dismiss="modal" aria-label="Close">
                        <i class="fa-solid fa-xmark"></i>
                    </button>
                </div>
                <!-- API -->
                <form action="{% url 'baseapp:add_request' %}" method="get" id="formCallback">
                    {% csrf_token %}
                    <div class="modal-body">
                        <label for="formCallbackPhone">Укажите Ваш номер телефона:</label>
                        <input id="formCallbackPhone" name="phone_number" class="input" type="text" required>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-primary" value="Заказать обратный звонок">
                    </div>
                </form>
            </div>
        </div>
    </div>
</header>

baseapp/templates/layout/headers.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="yandex-verification" content="e0db896e60b8e41e" />
<meta name="keywords" content="{{ keywords }}" />
<meta name="description" content="{{ description }}" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>
        {% if maintitle %}
                {{ maintitle }}
        {% elif product %}
                {{ product.title }}
        {% elif category %}
            {{ category.title }}
        {% else %}
            Главная
        {% endif %}
</title>

<link rel="shortcut icon" href="{% static 'baseapp/images/favicon.png' %}" type="image/png">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">

<script src="https://kit.fontawesome.com/b0f9a95edf.js" crossorigin="anonymous"></script>
<link href="{% static 'baseapp/css/main.css' %}" rel="stylesheet"></head>

baseapp/templates/layout/nav_categogies.html
{% for category in categories %}
    <a href="{% url 'baseapp:categorylist' id=category.id %}" class="nav-link">{{ category.title|capfirst }}</a>
{% endfor %}
    <a href="{% url 'baseapp:photoorder' %}" class="nav-link">Заказ по фото</a>
    <a href="{% url 'baseapp:photoalbum' %}" class="nav-link">Фотогалерея</a>

baseapp/templates/layout/navigation.html
{% load static %}
<div id="nav" class="nav">
    <div class="container">
        <div class="nav-inner">
            <div class="nav-wrapper">
                <!-- категории -->
                <div class="nav-categories">
                    <!-- 
                    <div class="nav-categories-link">
                        <i class="fa-solid fa-grip"></i>
                        Каталог орденских наград
                    </div>
                    -->
                    <div class="nav-categories-list">
                        <div class="container">
                            <div class="nav-categories-list-wrapper">
                                <!-- здесь перечислить категории -->
                                {% include "layout/nav_categogies.html" %}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- меню -->
                <a href="" class="nav-item nav-menu-link">
                    <i class="fa-solid fa-bars"></i>
                    Меню
                </a>

                <div id="nav-menu" class="nav-menu" data-is-opened="0">
                    <div class="nav-menu-close fa-xl">
                        <i class="fa-solid fa-xmark"></i>
                    </div>

                    <div class="site-search nav-search" data-method="GET" data-url="search">
                        <!-- API 11 -->
                        <form action="{% url 'baseapp:searchprod' %}" method="get">
                            <input class="site-search-input header-search" name="query" type="text" value="" placeholder="Поиск по сайту"/>
                            <a class="site-search-btn">
                                <i class="fa-solid fa-magnifying-glass"></i>
                            </a>
                        </form>
                    </div>
                    {% include "layout/nav_categogies.html" %}
                    
                </div>

            </div>

            <!-- корзина -->
            <!-- API -->
            <a href="{% url 'cart:cart' %}">
                <cart></cart>
            </a>
        </div>
    </div>

    {% include "layout/broat.html" %}
</div>

baseapp/templates/layout/services.html
{% load static %}
<section class="section services">
    <div class="container">
        <h2 class="section-title service-title">Наши услуги</h2>

        <!-- ссылки дублируются в каждой карточке в названии (это нужно для мобильной версии) -->
        <div class="row" style="gap: 20px 0;">
            {% for category in categories %}
            <div class="col-12 col-sm-6 col-md-4">
                <a class="service-item" href="{% url 'baseapp:categorylist' id=category.id %}">
                    <h3 class="service-item-title">{{ category.title|capfirst }}</h3>
                    <img class="service-item-img" src="{{ category.image.url }}"/>
                    <div class="service-item-link">
                        Подробнее<i class="fa-solid fa-square-arrow-up-right"></i>
                    </div>
                </a>
            </div>
            {% endfor %}
            <div class="col-12 col-sm-6 col-md-4">
            <a class="service-item" href="{% url 'baseapp:photoalbum' %}">
                <h3 class="service-item-title">Лазерная гравировка</h3>
                <img class="service-item-img" src="{% static 'baseapp/images/prim2.jpg' %}"/>
                <div class="service-item-link">
                    Подробнее<i class="fa-solid fa-square-arrow-up-right"></i>
                </div>
            </a>
        </div>

        </div>
    </div>
</section>