apiapp/urls.py
from django.urls import path
from .views import products_list, products_list_selected, cartitems, productdetail, getparameters
from paymentsystem.views import createorder
app_name = 'apiapp'

urlpatterns = [
    path('products-list', products_list, name='products-list'),
    path('products-list-selected', products_list_selected, name='products-list-selected'),
    path('cart/items', cartitems, name='cartitems'),
    path('cart/do-order', createorder, name='do-order'),
    path('product/<int:id>', productdetail, name='productdetail'),
    path('parameters', getparameters, name='getparameters'),#список значений параметра товара
]

baseapp/urls.py
from django.urls import path
from . import views
from .sitemap import ProductViewSitemap, CategoriesViewSitemap
from django.views.generic import RedirectView
from django.contrib.sitemaps.views import sitemap
app_name = 'baseapp'

sitemaps = {
    'dynamic': ProductViewSitemap,
    'category' :CategoriesViewSitemap,
}

favicon_view = RedirectView.as_view(url='/static/favicon.png', permanent=True)

urlpatterns = [
    path('robots.txt/', views.RobotsTxtView.as_view()),
    path('favicon.ico/', favicon_view),
    path('', views.index, name='home'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('category/<int:id>', views.categorylist, name='categorylist'),
    path('categoryselected', views.categoryselected, name='categoryselected'),
    path('add_request', views.add_request, name='add_request'),
    path('searchprod', views.searchprod, name='searchprod'),
    path('paymentsusses', views.paysus, name='paysus'),
    path('photoorder', views.photoorder, name='photoorder'),
    path('photoalbum', views.photoalbum, name='photoalbum'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
]

medals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baseapp.urls', namespace='baseapp')),
    path('cart/', include('ordersapp.urls', namespace='cart')),
    path('api/', include('apiapp.urls', namespace='apiapp')),
    path('payment/', include('paymentsystem.urls', namespace='payment')),
]

if settings.DEBUG:# не кешировать
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paymentsystem/urls.py
from django.urls import path
from .views import paymentstate, photoordersave
from paymentsystem.views import createorder
app_name = 'paymentsystem'

urlpatterns = [
    path('status', paymentstate, name='paymentstate'),
    path('photoordersave', photoordersave, name='photoordersave'),
]

baseapp/models.py
from django.db import models
from PIL import Image
from medals.settings import STATIC_ROOT

# Create your models here.
INPUTKIND = [
    ('1', 'checkbox'),
    ('2', 'input'),
    ('3', 'select'),
    ]
# Модель категорий
class Categories(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Наименование вида товара')
    image = models.ImageField(blank=True, upload_to='categories/', verbose_name='Главное изображение вида товара')
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вид товара'
        verbose_name_plural = 'Виды товаров'
        ordering = ['title']

class Categorymedals(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Вид награды')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вид награды'
        verbose_name_plural = 'Виды наград'
        ordering = ['-id']

class Parameters(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Вид параметра')
    inputtype = models.CharField(blank=True, max_length=20, choices = INPUTKIND, verbose_name='Тип ввода')
    label = models.CharField(blank=False, max_length=180, verbose_name='Подпись')
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вид параметра'
        verbose_name_plural = 'Виды параметров'
        ordering = ['-id']

# Модель товаров
class Product(models.Model):
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name='Категория', related_name="category")
    medalcategory = models.ForeignKey(Categorymedals, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Вид награды', related_name="categorymedal")
    title = models.CharField(blank=False, max_length=180, verbose_name='Наименование товара')
    image = models.ImageField(blank=False, null=False, upload_to='products_imgs/', verbose_name='Главное изображение товара')
    price = models.IntegerField(blank=False, null=False, default=100, verbose_name='Цена')
    description = models.TextField(blank=True, null=True, verbose_name='Описание товара')
    parameters = models.ForeignKey(Parameters, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Параметр', related_name="parameter")

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return str(self.title)
    
    def save(self):
        super().save()
        img = Image.open(self.image.path)
        mask = Image.open(STATIC_ROOT + '/mask.png')
        mask_crop = mask.crop((0, 0, img.width, img.height))
        img.paste(mask_crop, (0, 0), mask_crop)
        img.save(self.image.path)

# Модель дополнительных изображений товаров
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='товар', related_name="imgs")
    image = models.ImageField(blank=True, upload_to='product_imgs/', verbose_name='Дополнительное изображение')
    
    class Meta:
        verbose_name = 'Дополнительное изображение'
        verbose_name_plural = 'Дополнительные изображения'

    def __str__(self):
        return str(self.image.url)
    
    def save(self):
        super().save()
        img = Image.open(self.image.path)
        mask = Image.open('mask.png')
        mask_crop = mask.crop((0, 0, img.width, img.height))
        img.paste(mask_crop, (0, 0), mask_crop)
        img.save(self.image.path)
    

class Callrequest(models.Model):
    number = models.CharField(blank=False, null=False, max_length=80, verbose_name='Номер телефона')
    dateandtame = models.DateTimeField(blank=False, null=False, auto_now_add=True, verbose_name='Дата и время')

    class Meta:
        verbose_name = 'Заказ обратного звонка'
        verbose_name_plural = 'Заказы обратного звонка'

    def __str__(self):
        return str(self.number)
    

    
class Bases(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Наименование основы(крепления)')
    image = models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение крепления')
    requireColor = models.BooleanField(default=False, verbose_name="Нужен ли выбор цвета")
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вид крепления'
        verbose_name_plural = 'Виды креплений'
        ordering = ['title']

class Examples(models.Model):
    title = models.CharField(blank=False, max_length=180, verbose_name='Заголовок')
    about = models.TextField(blank=False, max_length=180, verbose_name='Описание')
    image = models.ImageField(blank=True, upload_to='examples/', verbose_name='Изображение')
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пример работы (слайдер)'
        verbose_name_plural = 'Примеры работ (слайдер)'
        ordering = ['title']

class ExampleImage(models.Model):
    image = models.ImageField(blank=True, upload_to='photogallery/', verbose_name='Фото фотогалереи')
    
    class Meta:
        verbose_name = 'Фото фотогалереи'
        verbose_name_plural = 'Фото фотогалереи'

    def __str__(self):
        return str(self.image.url)
    
    def save(self):
        super().save()
        img = Image.open(self.image.path)
        mask = Image.open(STATIC_ROOT + '/mask.png')
        mask_crop = mask.crop((0, 0, img.width, img.height))
        img.paste(mask_crop, (0, 0), mask_crop)
        img.save(self.image.path)

baseapp/views.py
from django.shortcuts import render, get_object_or_404
from datetime import datetime
from .models import Product, ProductImage, Categories, Categorymedals, Callrequest, Examples, ExampleImage
from paymentsystem.models import Orders
from django.db.models import Q
import urllib.request
import urllib.parse
from django.views.generic import TemplateView

# Create your views here.
def index(request):
    keywords = 'Орденские планки колодки крепления заказать купить Москва, купить Медали России, лазерная гравировка в Москве'
    description = 'Мы предлагаем широкий ассортимент орденских планок и колодок, услуги лазерной гравировки.'
    examples = Examples.objects.all()
    maintitle = 'Орденские планки и колодки лазерная гравировка'
    return render(request, 'baseapp/home.html', {
        'categories': categorytonav(),
        'keywords': keywords,
        'description': description,
        'examples': examples,
        'maintitle': maintitle,
    })

def detail(request, id):
    itemId = id
    product = get_object_or_404(Product, pk = itemId)
    imgs = product.imgs.all()
    broads = []
    print(product.category.id)
    broads.append(f'<li class="breadcrumb-item"><a href="../category/{ product.category.id }">{product.category}</a></li>')
    broads.append(f'<li class="breadcrumb-item active">{product.title}</li>')
    if product.category.id == 4:
        keywords = f'{product.title}, купить {product.title}, заказать планку {product.title} в Москве, купить планку {product.title}, {product.title} на офисную форму'
        description = f'В магазине планки.москва Вы можете заказать орденскую планку или колодку {product.title} на различных видах креплений и подложке'
    elif product.category.id == 5:
        keywords = f'купить {product.title}, заказать {product.title}, купить жетон с гравировкой номера в Москве, {product.title} гравировка'
        description = f'В магазине планки.москва Вы можете заказать {product.title} с гравировкой номера'
    elif product.category.id == 6:
        keywords = f'купить {product.title}, заказать {product.title}, купить нагрудный знак с гравировкой номера в Москве, {product.title} гравировка'
        description = f'В магазине планки.москва Вы можете заказать {product.title} с гравировкой номера'
    elif product.category.id == 7:
        keywords = f'купить сувенирный {product.title} в Москве, заказать {product.title} сувенирный, {product.title} в Москве'
        description = f'В магазине планки.москва Вы можете заказать {product.title} с гравировкой номера'
    elif product.category.id == 9:
        keywords = f'купить расходные материалы для изготовления орденских планок и колодок {product.title} в Москве'
        description = f'В магазине планки.москва Вы можете заказать или купить расходные материалы для изготовления орденских планок и колодок'
    else:
        keywords = f'{product.title}, купить {product.title}, заказать планку {product.title}, купить планку {product.title}, {product.title} на офисную форму'
        description = f'В магазине планки.москва Вы можете заказать орденскую планку или колодку {product.title} на различных видах креплений и подложке'
    return render(request, 'baseapp/detail.html', {
        'product': product,
        'categories': categorytonav(),
        'imgs': imgs,
        'broads': broads,
        'keywords': keywords,
        'description': description,
        })

def categorylist(request, id):
    categoryId = id
    category = get_object_or_404(Categories, pk = categoryId)
    broads = []
    broads.append(f'<li class="breadcrumb-item active">{category.title}</li>')
    medalstypes = Categorymedals.objects.all()
    keywords = f'{category.title}, заказать {category.title} в Москве'
    description = f'В магазине планки.москва Вы можете заказать {category.title}'
    return render(request, 'baseapp/catalog.html', {
        'categories': categorytonav(),
        'medalstypes': medalstypes,
        'category': category,
        'broads': broads,
        'keywords': keywords,
        'description': description,
        })

def categoryselected(request):
    if 'category' in request.GET:
        categoryId = request.GET['category']
    else:
        categoryId = '1'
    if 'itemtype' in request.GET:
        medaltypeId = request.GET['itemtype']
    else:
        medaltypeId = '1'
    medalstypes = Categorymedals.objects.all()
    category = get_object_or_404(Categories, pk = categoryId)
    keywords = f'{category.title}, заказать {category.title} в Москве'
    description = f'В магазине планки.москва Вы можете заказать {category.title}'
    broads = []
    broads.append(f'<li class="breadcrumb-item active">{category.title}</li>')
    return render(request, 'baseapp/catalog.html', {
        'categories': categorytonav(),
        'medalstypes': medalstypes,
        'medaltypeId': medaltypeId,
        'category': category,
        'keywords': keywords,
        'description': description,
        'broads': broads,
        })

def add_request(request):
    if request.method == 'GET':
        req = Callrequest()
        num = str(request.GET['phone_number'])
        req.number = num
        req.save()

        url = u'https://api.telegram.org/bot6359888423:AAGEfUcoYBAcutK4DzvSjkmlfxmPNh23qPQ/sendMessage'
        admins = ('628257666', '701668128',)
        trans_table = {ord(' ') : None, ord('-') : None, ord('(') : None, ord(')') : None}
        num = num.translate(trans_table)
        msgForTg = f'Заказан обратный звонок на номер {num}'
        for admin in admins:
            data = {'chat_id': admin, 'text': msgForTg, 'parse_mode': 'HTML'}
            url_values = urllib.parse.urlencode(data)
            full_url = url + '?' + url_values
            data = urllib.request.urlopen(full_url)
    return index(request)

def searchprod(request):
    search_query = request.GET.get('query')
    products = Product.objects.filter(Q(title__iregex=search_query))
    return render(request, 'baseapp/search.html', {
        'categories': categorytonav(),
        'products': products
        })

def photoorder(request):
    broads = []
    broads.append(f'<li class="breadcrumb-item active">Заказ по фото</li>')
    keywords = f'медаль заказать по фото, заказать изготовление планки'
    description = f'В магазине планки.москва Вы можете заказать орденскую планку по фото.'
    maintitle = 'Заказать орденскую планку по фото'
    return render(request, 'baseapp/photoorder.html', {
        'categories': categorytonav(),
        'broads': broads,
        'keywords': keywords,
        'description': description,
        'maintitle': maintitle,
        })

def photoalbum(request):
    photos = ExampleImage.objects.all()
    return render(request, 'baseapp/photoalbum.html', {
        'categories': categorytonav(),
        'photos': photos,
        })

def categorytonav():
    categories = Categories.objects.all()
    return categories

def paysus(request):
    order = get_object_or_404(Orders, pk = request.GET['order'])
    return render(request, 'baseapp/paysus.html', {
        'categories': categorytonav(),
        'order': order
        })

class RobotsTxtView(TemplateView):
    template_name = 'robots.txt'
    content_type = 'text/plain'

baseapp/templates/baseapp/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "layout/headers.html" %}
</head>
<body>
    {% csrf_token %}
<div id="app" class="wrapper">
    <notification></notification>

    <div class="content">
        {% include "layout/header.html" %}
        {% include "layout/navigation.html" %}
        <!----------------------------------------------------------------------------------------------------------------------------->
        <div class="section catalog">
            <div class="container">

                <div class="section-title catalog-title">{{ category.title }} от магазина планки.москва </div>
                {% if category.id == 4 %}
                <div class="catalog-sections">
                    <div class="catalog-sections-btn">
                        <i class="fa-solid fa-list"></i>
                        Категории
                    </div>

                    <div class="catalog-sections-list" data-is-active="0">
                        {% for type in medalstypes %}
                            <a href="../categoryselected?category={{ category.id }}&itemtype={{ type.id }}" class="catalog-sections-list-item">{{ type.title }}</a>
                        {% endfor %}
                        
                    </div>
                </div>
                {% endif %}
                <!-- API -->
                <catalog
                    :show-actions="true"
                    {% if medaltypeId %}
                        :products-api="'{% url 'apiapp:products-list-selected' %}?category={{ category.id }}&itemtype={{ medaltypeId }}'"
                    {% else %}
                        :products-api="'{% url 'apiapp:products-list' %}?category={{ category.id }}'"
                    {% endif %}
                ></catalog>
            </div>
        </div>
        <!----------------------------------------------------------------------------------------------------------------------------->

    </div>

    {% include "layout/footer.html" %}
</div>

<script type="application/javascript" defer src="{% static 'baseapp/js/bundle.js' %}"></script>
<script type="application/javascript" src="//code.jivo.ru/widget/vr84HCIabX" async></script>
</body>
</html>

baseapp/templates/baseapp/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "layout/headers.html" %}
</head>
<body>
    {% csrf_token %}
<div id="app" class="wrapper">
    <notification></notification>

    <div class="content">
        {% include "layout/header.html" %}
        {% include "layout/navigation.html" %}
        <!----------------------------------------------------------------------------------------------------------------------------->
        <div class="detail catalog">
            <div class="container">
                <div class="detail-body">
                    <div class="row">

                        <!-- писание -->
                        <div class="col-12 col-md-6 order-1 order-md-0 detail-main">
                            <div class="detail-subtitle">{{ product.title }}</div>
                            <div class="detail-price">{{ product.price }} ₽</div>
                            <div class="detail-sep"></div>
                            <div class="detail-section-list">
                                <a href="catalog.html" class="detail-section">{{ product.category }}</a>
                            </div>
                            <div class="detail-description">
                                <strong>Описание:</strong><br>
                                {{ product.description }}
                            </div>

                            <div class="detail-product">
                                <product :id="{{ product.id }}"></product>
                            </div>
                        </div>

                        <!-- картинки -->
                        <div class="col-12 col-md-6 order-0 order-md-1">
                            <div class="detail-img--main">
                                <!-- здесь основная картинка, она обязательно должна быть -->
                                <a href="{{ product.image.url }}" data-fancybox="gallery" data-caption="{{ product.description }}">
                                    <img src="{{ product.image.url }}" alt="купить {{ product.title }} в Москве" />
                                </a>
                            </div>

                            <div class="detail-img--second">
                                <!-- здесь должны быть перечислены другие картинки, вообще этого блока может и не быть -->
                                {% for image in imgs %}
                                <a href="{{ image.image.url }}" data-fancybox="gallery"
                                   data-caption="{{ product.description }}">
                                    <img src="{{ image.image.url }}" alt="заказать {{ product.title }} в Москве"/>
                                </a>
                                {% endfor %}
                               
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
        <!----------------------------------------------------------------------------------------------------------------------------->

    </div>

    {% include "layout/footer.html" %}
</div>

<script type="application/javascript" defer src="{% static 'baseapp/js/bundle.js' %}"></script>
<script type="application/javascript" src="//code.jivo.ru/widget/vr84HCIabX" async></script>
</body>
</html>

baseapp/templates/baseapp/home.html
{% extends "layout/base.html" %}
{% load static %}

baseapp/templates/baseapp/paysus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "layout/headers.html" %}
</head>
<body>
    {% csrf_token %}
<div id="app" class="wrapper">
    <notification></notification>
        {% include "layout/header.html" %}
        {% include "layout/navigation.html" %}
        <!----------------------------------------------------------------------------------------------------------------------------->
        <section class="section info">
                <div class="container">
                    <h2 class="info-title">Ваш заказ № {{ order.id }}</h2>
                    <div class="info-subtitle">на сумму {{ order.sumcost }} р.</div>
                    <div class="info-paragraph">в ожидании подтверждения.</div>
                    <div class="info-icon">
                        <i class="fa-solid fa-check fa-xl"></i>
                        <div>Денежные средства зарезервированы до подтверждения заказа</div>
                    </div>
                    <br>
                    <div class="info-paragraph">после проверки заказа мы свяжемся с Вами.</div>
                    <div class="info-paragraph">для дополнительной информации о статусе заказа Вы можете связаться с нами по номеру
                        <a href="tel:+79652960909">8 (965) 296-09-09</a>
                    </div>
                </div>
            </section>
        <!----------------------------------------------------------------------------------------------------------------------------->

    {% include "layout/footer.html" %}
</div>
<script>
    localStorage.setItem("cart", "{}");
</script>
<script type="application/javascript" defer src="{% static 'baseapp/js/bundle.js' %}"></script>
<script type="application/javascript" src="//code.jivo.ru/widget/vr84HCIabX" async></script>
</body>
</html>

baseapp/templates/baseapp/photoalbum.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "layout/headers.html" %}
</head>
<body>
    {% csrf_token %}
<div id="app" class="wrapper">
    <notification></notification>

    <div class="content">
        {% include "layout/header.html" %}
        {% include "layout/navigation.html" %}
        <!----------------------------------------------------------------------------------------------------------------------------->
        <section class="section photo">
            <div class="container">
                <h2 class="photo-title">Галерея работ от планки.Москва</h2>
                <div class="photo-list">
                    {% for photo in photos %}
                        <img src="{{ photo.image.url }}" alt="" data-fancybox="list-1">
                    {% endfor %}
                </div>
            </div>
        </section>
        <!----------------------------------------------------------------------------------------------------------------------------->

    </div>

    {% include "layout/footer.html" %}
</div>

<script type="application/javascript" defer src="{% static 'baseapp/js/bundle.js' %}"></script>
<script type="application/javascript" src="//code.jivo.ru/widget/vr84HCIabX" async></script>
</body>
</html>

baseapp/templates/baseapp/photoorder.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% include "layout/headers.html" %}
</head>

<body>
    {% csrf_token %}
    <div id="app" class="wrapper">
        <notification></notification>
        {% include "layout/header.html" %}
        {% include "layout/navigation.html" %}
        <div style='position: relative;'>
            <section class="section contacts">
                <div class="container">
                    <h1 class="section-title contacts-title info-title">Заказ по фото</h1>
                    <div class="row" style="gap: 20px 0">
                        <div class="col-12 col-md-6">
                            <section class="section info">
                                <div class="container">
                                    <div class="info-subtitle">У нас Вы можете заказать орденские планки и колодки лишь загрузив их фото.</div>
                                    <div class="info-paragraph">Для заказа орденских планок и колодок по фото ведите адрес электронной почты и номер телефона.</div>
                                    <div class="info-paragraph">Нажмите "Выберите файлы", выделите все нужные фотографии и добавьте. Затем нажмите "Оформить заказ".</div>
                                    <div class="info-paragraph">После получения фотографий Мы рассчитаем стоимость и свяжемся с Вами.</div>
                                </div>
                            </section>
                        </div>
                        <div class="col-12 col-md-6">

                            <section class="section order">
                                <div class="container">
                                    <h2 class="section-title order-title">Заказать по фото</h2>
                
                                    <form method="post" action="{% url 'payment:photoordersave' %}" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="order-wrapper">
                
                                            <div class="order-form-group">
                                                <label for="formOrderPhone">Номер телефона</label>
                                                <input id="formOrderPhone" name="phone" class="input" type="text" required>
                                            </div>
                
                                            <div class="order-form-group">
                                                <label for="email">Email</label>
                                                <input id="email" name="email" class="input" type="email" required>
                                            </div>
                
                                            <div class="order-form-group">
                                                <label for="images">Файлы фотографий</label>
                                                <div class="input-group custom-file-button">
                                                    <label class="input-group-text" for="images">Выберите файлы</label>
                                                    <input class="form-control2" type="file" id="images" name="images"
                                                           accept="image/jpeg, image/png, image/jpg" required multiple>
                                                </div>
                                            </div>
                
                                            <input class="btn submit" type="submit" value="Оформить заказ">
                                        </div>
                                    </form>
                                </div>
                            </section>
                            
                        </div>
                    </div>
                </div>
            </section>
        </div>

    </div>

    {% include "layout/footer.html" %}
    </div>
    <script type="application/javascript" defer src="{% static 'baseapp/js/bundle.js' %}"></script>
    <script type="application/javascript" src="//code.jivo.ru/widget/vr84HCIabX" async></script>
</body>

</html>

baseapp/templates/baseapp/photosucess.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "layout/headers.html" %}
</head>
<body>
    {% csrf_token %}
<div id="app" class="wrapper">
    <notification></notification>
        {% include "layout/header.html" %}
        {% include "layout/navigation.html" %}
        <!----------------------------------------------------------------------------------------------------------------------------->
        <section class="section info">
                <div class="container">
                    <h2 class="info-title">Ваш заказ № {{ order.id }}</h2>
                    <div class="info-paragraph">в ожидании подтверждения.</div>
                    <div class="info-icon">
                        <i class="fa-solid fa-check fa-xl"></i>
                        <div>Изображение загружено</div>
                    </div>
                    <br>
                    <div class="info-paragraph">после проверки заказа мы свяжемся с Вами.</div>
                    <div class="info-paragraph">для дополнительной информации о статусе заказа Вы можете связаться с нами по номеру
                        <a href="tel:+79652960909">8 (965) 296-09-09</a>
                    </div>
                </div>
            </section>
        <!----------------------------------------------------------------------------------------------------------------------------->

    {% include "layout/footer.html" %}
</div>
<script>
    localStorage.setItem("cart", "{}");
</script>
<script type="application/javascript" defer src="{% static 'baseapp/js/bundle.js' %}"></script>
<script type="application/javascript" src="//code.jivo.ru/widget/vr84HCIabX" async></script>
</body>
</html>